In [1]:
#Implementando el Análisis de Clústeres con K-Means(Caso Centro Comercial)
#Objetivo: aplicar KMeans para crear 3 clusters en datos estandarizados, añadir la asignación de clusters a tus datos, 
#realizar un análisis agrupado por cluster y finalmente interpretar los resultados, asistido por ChatGPT.

In [2]:
# Importamos Bibliotecas

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [3]:
# Carga de datos desde un archivo CSV

datos = pd.read_csv('C:\\Users\\ALLAN\\Desktop\\Business Analitics con Python y ChatGPT\\centrocomercial.csv', delimiter = ';', index_col = 'ID')

In [4]:
datos.head()

       Genero  Edad  IngresoAnual  ScoreGasto
ID
1   Masculino    19            15          39
2   Masculino    21            15          81
3    Femenino    20            16           6
4    Femenino    23            16          77
5    Femenino    31            17          40

In [5]:
# Preprocesamiento de datos categóricos:
# Convertir la variable categórica 'Genero' en variables dummy/indicadoras.
# 'drop_first=True' omite la primera categoría alfabética para evitar la multicolinealidad,
# lo que significa que 'Femenino' será representado como 0 y 'Masculino' como 1.

In [6]:
datos_preprocesados = pd.get_dummies(datos, columns=['Genero'], drop_first=True)

In [7]:
datos_preprocesados.head()

    Edad  IngresoAnual  ScoreGasto  Genero_Masculino
ID
1     19            15          39              True
2     21            15          81              True
3     20            16           6             False
4     23            16          77             False
5     31            17          40             False

In [8]:
# Estandarización de los datos numéricos:
# Inicializar un objeto StandardScaler

estandarizar = StandardScaler()

In [9]:
# Aplicar la estandarización

datos_std = estandarizar.fit_transform(datos_preprocesados)

In [10]:
datos_std

array([[-1.42456879, -1.73899919, -0.43480148,  1.12815215],
       [-1.28103541, -1.73899919,  1.19570407,  1.12815215],
       [-1.3528021 , -1.70082976, -1.71591298, -0.88640526],
       [-1.13750203, -1.70082976,  1.04041783, -0.88640526],
       [-0.56336851, -1.66266033, -0.39597992, -0.88640526],
       [-1.20926872, -1.66266033,  1.00159627, -0.88640526],
       [-0.27630176, -1.62449091, -1.71591298, -0.88640526],
       [-1.13750203, -1.62449091,  1.70038436, -0.88640526],
       [ 1.80493225, -1.58632148, -1.83237767,  1.12815215],
       [-0.6351352 , -1.58632148,  0.84631002, -0.88640526],
       [ 2.02023231, -1.58632148, -1.4053405 ,  1.12815215],
       [-0.27630176, -1.58632148,  1.89449216, -0.88640526],
       [ 1.37433211, -1.54815205, -1.36651894, -0.88640526],
       [-1.06573534, -1.54815205,  1.04041783, -0.88640526],
       [-0.13276838, -1.54815205, -1.44416206,  1.12815215],
       [-1.20926872, -1.54815205,  1.11806095,  1.12815215],
       [-0.27630176, -1.50998262, -0.59008772, -0.88640526],
       [-1.3528021 , -1.50998262,  0.61338066,  1.12815215],
       [ 0.94373197, -1.43364376, -0.82301709,  1.12815215],
       [-0.27630176, -1.43364376,  1.8556706 , -0.88640526],
       [-0.27630176, -1.39547433, -0.59008772,  1.12815215],
       [-0.99396865, -1.39547433,  0.88513158,  1.12815215],
       [ 0.51313183, -1.3573049 , -1.75473454, -0.88640526],
       [-0.56336851, -1.3573049 ,  0.88513158,  1.12815215],
       [ 1.08726535, -1.24279661, -1.4053405 , -0.88640526],
       [-0.70690189, -1.24279661,  1.23452563,  1.12815215],
       [ 0.44136514, -1.24279661, -0.7065524 , -0.88640526],
       [-0.27630176, -1.24279661,  0.41927286,  1.12815215],
       [ 0.08253169, -1.20462718, -0.74537397, -0.88640526],
       [-1.13750203, -1.20462718,  1.42863343, -0.88640526],
       [ 1.51786549, -1.16645776, -1.7935561 ,  1.12815215],
       [-1.28103541, -1.16645776,  0.88513158, -0.88640526],
       [ 1.01549866, -1.05194947, -1.7935561 ,  1.12815215],
       [-1.49633548, -1.05194947,  1.62274124,  1.12815215],
       [ 0.7284319 , -1.05194947, -1.4053405 , -0.88640526],
       [-1.28103541, -1.05194947,  1.19570407, -0.88640526],
       [ 0.22606507, -1.01378004, -1.28887582, -0.88640526],
       [-0.6351352 , -1.01378004,  0.88513158, -0.88640526],
       [-0.20453507, -0.89927175, -0.93948177, -0.88640526],
       [-1.3528021 , -0.89927175,  0.96277471, -0.88640526],
       [ 1.87669894, -0.86110232, -0.59008772, -0.88640526],
       [-1.06573534, -0.86110232,  1.62274124,  1.12815215],
       [ 0.65666521, -0.82293289, -0.55126616,  1.12815215],
       [-0.56336851, -0.82293289,  0.41927286, -0.88640526],
       [ 0.7284319 , -0.82293289, -0.86183865, -0.88640526],
       [-1.06573534, -0.82293289,  0.5745591 , -0.88640526],
       [ 0.80019859, -0.78476346,  0.18634349, -0.88640526],
       [-0.85043527, -0.78476346, -0.12422899, -0.88640526],
       [-0.70690189, -0.78476346, -0.3183368 , -0.88640526],
       [-0.56336851, -0.78476346, -0.3183368 , -0.88640526],
       [ 0.7284319 , -0.70842461,  0.06987881, -0.88640526],
       [-0.41983513, -0.70842461,  0.38045129,  1.12815215],
       [-0.56336851, -0.67025518,  0.14752193, -0.88640526],
       [ 1.4460988 , -0.67025518,  0.38045129,  1.12815215],
       [ 0.80019859, -0.67025518, -0.20187212, -0.88640526],
       [ 0.58489852, -0.67025518, -0.35715836,  1.12815215],
       [ 0.87196528, -0.63208575, -0.00776431, -0.88640526],
       [ 2.16376569, -0.63208575, -0.16305055,  1.12815215],
       [-0.85043527, -0.55574689,  0.03105725, -0.88640526],
       [ 1.01549866, -0.55574689, -0.16305055,  1.12815215],
       [ 2.23553238, -0.55574689,  0.22516505,  1.12815215],
       [-1.42456879, -0.55574689,  0.18634349,  1.12815215],
       [ 2.02023231, -0.51757746,  0.06987881, -0.88640526],
       [ 1.08726535, -0.51757746,  0.34162973, -0.88640526],
       [ 1.73316556, -0.47940803,  0.03105725,  1.12815215],
       [-1.49633548, -0.47940803,  0.34162973,  1.12815215],
       [ 0.29783176, -0.47940803, -0.00776431, -0.88640526],
       [ 2.091999  , -0.47940803, -0.08540743, -0.88640526],
       [-1.42456879, -0.47940803,  0.34162973,  1.12815215],
       [-0.49160182, -0.47940803, -0.12422899, -0.88640526],
       [ 2.23553238, -0.4412386 ,  0.18634349,  1.12815215],
       [ 0.58489852, -0.4412386 , -0.3183368 , -0.88640526],
       [ 1.51786549, -0.40306917, -0.04658587, -0.88640526],
       [ 1.51786549, -0.40306917,  0.22516505, -0.88640526],
       [ 1.4460988 , -0.25039146, -0.12422899,  1.12815215],
       [-0.92220196, -0.25039146,  0.14752193,  1.12815215],
       [ 0.44136514, -0.25039146,  0.10870037, -0.88640526],
       [ 0.08253169, -0.25039146, -0.08540743,  1.12815215],
       [-1.13750203, -0.25039146,  0.06987881, -0.88640526],
       [ 0.7284319 , -0.25039146, -0.3183368 , -0.88640526],
       [ 1.30256542, -0.25039146,  0.03105725,  1.12815215],
       [-0.06100169, -0.25039146,  0.18634349,  1.12815215],
       [ 2.02023231, -0.25039146, -0.35715836,  1.12815215],
       [ 0.51313183, -0.25039146, -0.24069368, -0.88640526],
       [-1.28103541, -0.25039146,  0.26398661, -0.88640526],
       [ 0.65666521, -0.25039146, -0.16305055,  1.12815215],
       [ 1.15903204, -0.13588317,  0.30280817, -0.88640526],
       [-1.20926872, -0.13588317,  0.18634349, -0.88640526],
       [-0.34806844, -0.09771374,  0.38045129, -0.88640526],
       [ 0.80019859, -0.09771374, -0.16305055, -0.88640526],
       [ 2.091999  , -0.05954431,  0.18634349, -0.88640526],
       [-1.49633548, -0.05954431, -0.35715836,  1.12815215],
       [ 0.65666521, -0.02137488, -0.04658587,  1.12815215],
       [ 0.08253169, -0.02137488, -0.39597992, -0.88640526],
       [-0.49160182, -0.02137488, -0.3183368 , -0.88640526],
       [-1.06573534, -0.02137488,  0.06987881,  1.12815215],
       [ 0.58489852, -0.02137488, -0.12422899, -0.88640526],
       [-0.85043527, -0.02137488, -0.00776431, -0.88640526],
       [ 0.65666521,  0.01679455, -0.3183368 ,  1.12815215],
       [-1.3528021 ,  0.01679455, -0.04658587,  1.12815215],
       [-1.13750203,  0.05496398, -0.35715836, -0.88640526],
       [ 0.7284319 ,  0.05496398, -0.08540743, -0.88640526],
       [ 2.02023231,  0.05496398,  0.34162973,  1.12815215],
       [-0.92220196,  0.05496398,  0.18634349,  1.12815215],
       [ 0.7284319 ,  0.05496398,  0.22516505,  1.12815215],
       [-1.28103541,  0.05496398, -0.3183368 , -0.88640526],
       [ 1.94846562,  0.09313341, -0.00776431, -0.88640526],
       [ 1.08726535,  0.09313341, -0.16305055,  1.12815215],
       [ 2.091999  ,  0.09313341, -0.27951524,  1.12815215],
       [ 1.94846562,  0.09313341, -0.08540743,  1.12815215],
       [ 1.87669894,  0.09313341,  0.06987881,  1.12815215],
       [-1.42456879,  0.09313341,  0.14752193, -0.88640526],
       [-0.06100169,  0.13130284, -0.3183368 , -0.88640526],
       [-1.42456879,  0.13130284, -0.16305055,  1.12815215],
       [-1.49633548,  0.16947227, -0.08540743, -0.88640526],
       [-1.42456879,  0.16947227, -0.00776431, -0.88640526],
       [ 1.73316556,  0.16947227, -0.27951524, -0.88640526],
       [ 0.7284319 ,  0.16947227,  0.34162973, -0.88640526],
       [ 0.87196528,  0.24581112, -0.27951524, -0.88640526],
       [ 0.80019859,  0.24581112,  0.26398661, -0.88640526],
       [-0.85043527,  0.24581112,  0.22516505,  1.12815215],
       [-0.06100169,  0.24581112, -0.39597992, -0.88640526],
       [ 0.08253169,  0.32214998,  0.30280817, -0.88640526],
       [ 0.010765  ,  0.32214998,  1.58391968,  1.12815215],
       [-1.13750203,  0.36031941, -0.82301709, -0.88640526],
       [-0.56336851,  0.36031941,  1.04041783, -0.88640526],
       [ 0.29783176,  0.39848884, -0.59008772,  1.12815215],
       [ 0.08253169,  0.39848884,  1.73920592,  1.12815215],
       [ 1.4460988 ,  0.39848884, -1.52180518,  1.12815215],
       [-0.06100169,  0.39848884,  0.96277471,  1.12815215],
       [ 0.58489852,  0.39848884, -1.5994483 ,  1.12815215],
       [ 0.010765  ,  0.39848884,  0.96277471,  1.12815215],
       [-0.99396865,  0.43665827, -0.62890928, -0.88640526],
       [-0.56336851,  0.43665827,  0.80748846, -0.88640526],
       [-1.3528021 ,  0.4748277 , -1.75473454,  1.12815215],
       [-0.70690189,  0.4748277 ,  1.46745499, -0.88640526],
       [ 0.36959845,  0.4748277 , -1.67709142, -0.88640526],
       [-0.49160182,  0.4748277 ,  0.88513158,  1.12815215],
       [-1.42456879,  0.51299713, -1.56062674,  1.12815215],
       [-0.27630176,  0.51299713,  0.84631002, -0.88640526],
       [ 1.30256542,  0.55116656, -1.75473454, -0.88640526],
       [-0.49160182,  0.55116656,  1.6615628 ,  1.12815215],
       [-0.77866858,  0.58933599, -0.39597992, -0.88640526],
       [-0.49160182,  0.58933599,  1.42863343, -0.88640526],
       [-0.99396865,  0.62750542, -1.48298362,  1.12815215],
       [-0.77866858,  0.62750542,  1.81684904,  1.12815215],
       [ 0.65666521,  0.62750542, -0.55126616,  1.12815215],
       [-0.49160182,  0.62750542,  0.92395314, -0.88640526],
       [-0.34806844,  0.66567484, -1.09476801, -0.88640526],
       [-0.34806844,  0.66567484,  1.54509812,  1.12815215],
       [ 0.29783176,  0.66567484, -1.28887582,  1.12815215],
       [ 0.010765  ,  0.66567484,  1.46745499,  1.12815215],
       [ 0.36959845,  0.66567484, -1.17241113, -0.88640526],
       [-0.06100169,  0.66567484,  1.00159627, -0.88640526],
       [ 0.58489852,  0.66567484, -1.32769738, -0.88640526],
       [-0.85043527,  0.66567484,  1.50627656, -0.88640526],
       [-0.13276838,  0.66567484, -1.91002079,  1.12815215],
       [-0.6351352 ,  0.66567484,  1.07923939, -0.88640526],
       [-0.34806844,  0.66567484, -1.91002079,  1.12815215],
       [-0.6351352 ,  0.66567484,  0.88513158, -0.88640526],
       [ 1.23079873,  0.70384427, -0.59008772, -0.88640526],
       [-0.70690189,  0.70384427,  1.27334719, -0.88640526],
       [-1.42456879,  0.78018313, -1.75473454,  1.12815215],
       [-0.56336851,  0.78018313,  1.6615628 , -0.88640526],
       [ 0.80019859,  0.93286085, -0.93948177,  1.12815215],
       [-0.20453507,  0.93286085,  0.96277471, -0.88640526],
       [ 0.22606507,  0.97103028, -1.17241113,  1.12815215],
       [-0.41983513,  0.97103028,  1.73920592, -0.88640526],
       [-0.20453507,  1.00919971, -0.90066021, -0.88640526],
       [-0.49160182,  1.00919971,  0.49691598,  1.12815215],
       [ 0.08253169,  1.00919971, -1.44416206,  1.12815215],
       [-0.77866858,  1.00919971,  0.96277471,  1.12815215],
       [-0.20453507,  1.00919971, -1.56062674,  1.12815215],
       [-0.20453507,  1.00919971,  1.62274124,  1.12815215],
       [ 0.94373197,  1.04736914, -1.44416206, -0.88640526],
       [-0.6351352 ,  1.04736914,  1.38981187, -0.88640526],
       [ 1.37433211,  1.04736914, -1.36651894,  1.12815215],
       [-0.85043527,  1.04736914,  0.72984534,  1.12815215],
       [ 1.4460988 ,  1.23821628, -1.4053405 ,  1.12815215],
       [-0.27630176,  1.23821628,  1.54509812,  1.12815215],
       [-0.13276838,  1.390894  , -0.7065524 , -0.88640526],
       [-0.49160182,  1.390894  ,  1.38981187, -0.88640526],
       [ 0.51313183,  1.42906343, -1.36651894,  1.12815215],
       [-0.70690189,  1.42906343,  1.46745499, -0.88640526],
       [ 0.15429838,  1.46723286, -0.43480148, -0.88640526],
       [-0.6351352 ,  1.46723286,  1.81684904,  1.12815215],
       [ 1.08726535,  1.54357172, -1.01712489, -0.88640526],
       [-0.77866858,  1.54357172,  0.69102378,  1.12815215],
       [ 0.15429838,  1.61991057, -1.28887582, -0.88640526],
       [-0.20453507,  1.61991057,  1.35099031, -0.88640526],
       [-0.34806844,  1.61991057, -1.05594645, -0.88640526],
       [-0.49160182,  1.61991057,  0.72984534, -0.88640526],
       [-0.41983513,  2.00160487, -1.63826986,  1.12815215],
       [-0.06100169,  2.00160487,  1.58391968, -0.88640526],
       [ 0.58489852,  2.26879087, -1.32769738, -0.88640526],
       [-0.27630176,  2.26879087,  1.11806095, -0.88640526],
       [ 0.44136514,  2.49780745, -0.86183865, -0.88640526],
       [-0.49160182,  2.49780745,  0.92395314,  1.12815215],
       [-0.49160182,  2.91767117, -1.25005425,  1.12815215],
       [-0.6351352 ,  2.91767117,  1.27334719,  1.12815215]])

In [11]:
cluster3 = KMeans(n_clusters=3, init="k-means++", random_state=99)

In [12]:
#Ahora Entrenaré el Modelo de Datos Cluster(n=3)

cluster3.fit(datos_std)

C:\Users\ALLAN\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
C:\Users\ALLAN\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

KMeans(n_clusters=3, random_state=99)

In [13]:
# Añado las etiquetas de cluster a los datos preprocesados para su análisis
# Utilizo los datos preprocesados en lugar de los datos originales para poder analizar la variable categórica
# Creo una copia para conservar los datos originales sin alteración (una buena práctica)
# Utilizo los datos preprocesados en lugar de los datos originales para poder analizar la variable categórica

datos_copia = datos_preprocesados.copy()

In [14]:
# Y en el df copia, añadimos una nueva columna con el número del cluster

datos_copia['Cluster'] = cluster3.labels_

In [15]:
# Veamos que tiene datos_copia

datos_copia

     Edad  IngresoAnual  ScoreGasto  Genero_Masculino  Cluster
ID
1      19            15          39              True        0
2      21            15          81              True        0
3      20            16           6             False        1
4      23            16          77             False        0
5      31            17          40             False        1
..    ...           ...         ...               ...      ...
196    35           120          79             False        0
197    45           126          28             False        1
198    32           126          74              True        0
199    32           137          18              True        2
200    30           137          83              True        0

[200 rows x 5 columns]

In [16]:
# Crear una tabla de análisis agrupando por cluster (con .groupby) y calculando la media de las variables (con .mean)

df_analisis = datos_copia.groupby('Cluster').mean()

In [17]:
df_analisis

              Edad  IngresoAnual  ScoreGasto  Genero_Masculino
Cluster
0        28.107143     61.785714   73.261905          0.464286
1        44.746269     57.791045   36.253731          0.000000
2        49.204082     62.244898   29.734694          1.000000